import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#03245a',
  },
  scrollContent: {
    flexGrow: 1,
    alignItems: 'center',
    padding: 24,
    paddingBottom: 60,
  },
  header: {
    width: '100%',
    maxWidth: 900,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 14,
  },
  backButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: 'bold',
  },
  statsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  statBadge: {
    backgroundColor: 'rgba(255,255,255,0.15)',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 12,
  },
  statLabel: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 12,
    fontWeight: '600',
  },
  statValue: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  titleContainer: {
    alignItems: 'center',
    marginBottom: 28,
  },
  titleText: {
    fontSize: 34,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 6,
  },
  subTitleText: {
    fontSize: 16,
    color: 'rgba(255,255,255,0.8)',
    textAlign: 'center',
  },
  gridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 16,
    maxWidth: 680,
    width: '100%',
  },
  card: {
    width: 140,
    height: 140,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    boxShadow: '0px 6px 14px rgba(0, 0, 0, 0.25)',
  },
  cardMobile: {
    width: 100,
    height: 100,
    borderRadius: 16,
  },
  cardDown: {
    backgroundColor: '#0a3d8f',
    borderWidth: 2,
    borderColor: '#3b82f6',
  },
  cardUp: {
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#60a5fa',
  },
  cardMatched: {
    backgroundColor: '#ecfdf5',
    borderWidth: 2,
    borderColor: '#10b981',
  },
  cardEmoji: {
    fontSize: 44,
  },
  cardEmojiMobile: {
    fontSize: 32,
  },
  cardLabel: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#1e293b',
    marginTop: 6,
    textAlign: 'center',
  },
  cardLabelMatched: {
    color: '#047857',
  },
  cardBackEmoji: {
    fontSize: 40,
  },
  resetButton: {
    marginTop: 32,
    backgroundColor: '#1565c0',
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 16,
  },
  resetButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(3, 36, 90, 0.85)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    zIndex: 1000,
  },
  modalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    padding: 32,
    alignItems: 'center',
    maxWidth: 420,
    width: '100%',
    boxShadow: '0px 10px 30px rgba(0, 0, 0, 0.35)',
  },
  modalEmoji: {
    fontSize: 64,
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#0a3d8f',
    textAlign: 'center',
    marginBottom: 8,
  },
  modalSubtitle: {
    fontSize: 15,
    color: '#64748b',
    textAlign: 'center',
    marginBottom: 20,
  },
  rewardBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fef3c7',
    borderWidth: 1.5,
    borderColor: '#f59e0b',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 20,
    marginBottom: 24,
  },
  rewardEmoji: {
    fontSize: 24,
    marginRight: 10,
  },
  rewardText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#b45309',
  },
  modalPrimaryBtn: {
    backgroundColor: '#00897b',
    width: '100%',
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: 'center',
    marginBottom: 12,
  },
  modalPrimaryBtnText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: 'bold',
  },
  modalSecondaryBtn: {
    backgroundColor: '#EEF2FF',
    width: '100%',
    paddingVertical: 14,
    borderRadius: 16,
    alignItems: 'center',
  },
  modalSecondaryBtnText: {
    color: '#0a3d8f',
    fontSize: 15,
    fontWeight: 'bold',
  },
});
