import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f0f4ff',
  },
  scrollContent: {
    flexGrow: 1,
  },
  navbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 48,
    paddingVertical: 20,
    backgroundColor: '#0a3d8f',
  },
  navBrand: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  navEmoji: {
    fontSize: 28,
    marginRight: 10,
  },
  navTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  navActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  navLoginBtn: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 12,
  },
  navLoginText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
  },
  navSignUpBtn: {
    backgroundColor: '#00897b',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 12,
  },
  navSignUpText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: 'bold',
  },
  heroSection: {
    backgroundColor: '#0a3d8f',
    paddingVertical: 80,
    paddingHorizontal: 24,
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  bubble1: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(255,255,255,0.05)',
    top: -40,
    left: '10%',
  },
  bubble2: {
    position: 'absolute',
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: 'rgba(255,255,255,0.07)',
    bottom: 20,
    right: '15%',
  },
  bubble3: {
    position: 'absolute',
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(255,255,255,0.05)',
    top: 60,
    right: '25%',
  },
  heroBadge: {
    backgroundColor: 'rgba(255,255,255,0.15)',
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 20,
    marginBottom: 20,
  },
  heroBadgeText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  heroTitle: {
    fontSize: 48,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 16,
    maxWidth: 750,
    lineHeight: 56,
  },
  heroSubtitle: {
    fontSize: 18,
    color: 'rgba(255,255,255,0.85)',
    textAlign: 'center',
    maxWidth: 600,
    lineHeight: 28,
    marginBottom: 36,
  },
  heroButtonsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  primaryHeroBtn: {
    backgroundColor: '#00897b',
    paddingHorizontal: 28,
    paddingVertical: 16,
    borderRadius: 16,
    boxShadow: '0px 4px 14px rgba(0, 137, 123, 0.4)',
  },
  primaryHeroBtnText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  secondaryHeroBtn: {
    backgroundColor: 'rgba(255,255,255,0.15)',
    paddingHorizontal: 28,
    paddingVertical: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  secondaryHeroBtnText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
  },
  featuresSection: {
    paddingVertical: 64,
    paddingHorizontal: 48,
    alignItems: 'center',
    backgroundColor: '#f0f4ff',
  },
  featuresHeader: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#0a3d8f',
    marginBottom: 8,
    textAlign: 'center',
  },
  featuresSubHeader: {
    fontSize: 16,
    color: '#7a8aaa',
    marginBottom: 44,
    textAlign: 'center',
  },
  featuresGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 24,
    maxWidth: 1100,
    width: '100%',
  },
  featureCard: {
    flex: 1,
    minWidth: 260,
    maxWidth: 340,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 28,
    boxShadow: '0px 8px 24px rgba(0, 0, 0, 0.06)',
    alignItems: 'flex-start',
  },
  featureIconContainer: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#EEF2FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  featureIcon: {
    fontSize: 28,
  },
  featureTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1a2340',
    marginBottom: 8,
  },
  featureDesc: {
    fontSize: 14,
    color: '#64748b',
    lineHeight: 22,
  },
  footer: {
    backgroundColor: '#0a3d8f',
    paddingVertical: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerText: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 14,
  },
});
