// profile.style.ts
import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  gradientContainer: {
    flex: 1,
  },
  container: {
    flex: 1,
    paddingTop: Platform.OS === 'android' ? 30 : 0,
  },
  containerMobile: {
    paddingHorizontal: 16,
  },

  // ================= NAVBAR SUPERIOR (MÓVIL) =================
  headerRowMobile: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    paddingVertical: 12,
  },
  headerSideMobile: {
    flex: 1,
    justifyContent: 'center',
  },
  headerSideLeftMobile: {
    alignItems: 'flex-start',
  },
  headerSideRightMobile: {
    alignItems: 'flex-end',
  },
  headerCenterMobile: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileIconMobile: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 4,
  },
  profileIconImage: {
    width: 24,
    height: 24,
    resizeMode: 'contain',
  },

  // ================= NAVBAR SUPERIOR (WEB ESCRITORIO) =================
  topNavbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: 40,
    paddingVertical: 20,
    zIndex: 10,
  },
  headerSide: {
    flex: 1,
    justifyContent: 'center',
  },
  headerSideLeft: {
    alignItems: 'flex-start',
  },
  headerSideRight: {
    alignItems: 'flex-end',
  },
  headerCenter: {
    flex: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoCard: {
    flexDirection: 'row',
    alignItems: 'baseline',
    backgroundColor: '#ffffff',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 5,
  },
  logoTextTitle: {
    fontSize: 24,
    fontWeight: '900',
    color: '#0a3d8f',
  },
  logoTextSub: {
    fontSize: 24,
    fontWeight: '300',
    color: '#3b82f6',
  },
  navIsland: {
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    borderRadius: 35,
    padding: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 5,
  },
  navIslandMobile: {
    justifyContent: 'space-around',
    width: '100%',
    paddingVertical: 8,
  },
  navPill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 22,
    borderRadius: 30,
    marginHorizontal: 4,
  },
  navPillMobile: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    marginHorizontal: 0,
  },
  pillIcon: {
    width: 22,
    height: 22,
    resizeMode: 'contain',
    marginRight: 8,
  },
  pillIconMobile: {
    width: 24,
    height: 24,
    marginRight: 6,
  },
  pillText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1e293b',
  },
  pillTextMobile: {
    fontSize: 13,
  },
  coinsCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 5,
  },
  coinsCardMobile: {
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  coinIcon: {
    width: 26,
    height: 26,
    resizeMode: 'contain',
    marginRight: 8,
  },
  coinIconMobile: {
    width: 22,
    height: 22,
    marginRight: 6,
  },
  coinsText: {
    fontSize: 18,
    fontWeight: '900',
    color: '#1e293b',
  },
  coinsTextMobile: {
    fontSize: 16,
  },
  bottomNavbarMobile: {
    width: '100%',
    paddingVertical: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },

  // ================= CONTENIDO PERFIL =================
  scrollContent: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
    paddingHorizontal: 16,
  },
  profileCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    padding: 30,
    width: '100%',
    maxWidth: 520,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 15,
    elevation: 10,
  },
  avatarCircle: {
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: '#e0f2fe',
    borderWidth: 4,
    borderColor: '#3b82f6',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    shadowColor: '#3b82f6',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
    overflow: 'hidden',
  },
  avatarImage: {
    width: 120,
    height: 120,
    resizeMode: 'contain',
  },
  equippedBadge: {
    backgroundColor: '#10b981',
    paddingHorizontal: 18,
    paddingVertical: 6,
    borderRadius: 20,
    marginBottom: 24,
  },
  equippedBadgeText: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 14,
  },
  infoSection: {
    width: '100%',
  },
  fieldBox: {
    backgroundColor: '#f8fafc',
    borderRadius: 18,
    paddingHorizontal: 20,
    paddingVertical: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  fieldLabel: {
    fontSize: 13,
    color: '#64748b',
    fontWeight: '700',
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  fieldValue: {
    fontSize: 18,
    color: '#1e293b',
    fontWeight: 'bold',
  },
  passwordRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  toggleBtn: {
    backgroundColor: '#e2efff',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#bbf',
  },
  toggleBtnText: {
    color: '#1d4ed8',
    fontWeight: '800',
    fontSize: 13,
  },
  logoutButton: {
    backgroundColor: '#ef4444',
    paddingVertical: 18,
    borderRadius: 18,
    width: '100%',
    alignItems: 'center',
    marginTop: 12,
    shadowColor: '#ef4444',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 6,
  },
  logoutButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '900',
  },
});
