// store.style.ts
import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  gradientContainer: {
    flex: 1,
  },
  container: {
    flex: 1,
    paddingHorizontal: '4%',
    paddingTop: 20,
    width: '100%',
    alignSelf: 'center',
    maxWidth: 1400,
  },
  containerMobile: {
    paddingHorizontal: '5%',
    paddingTop: 45,
  },
  mainContentWeb: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 32,
    marginBottom: 20,
  },

  // ================= NAVBARS =================
  topNavbar: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 30,
    marginBottom: 15,
    zIndex: 50,
    paddingHorizontal: '5%',
  },
  headerSide: { flex: 1, flexDirection: 'row', alignItems: 'center' },
  headerSideLeft: { justifyContent: 'flex-start' },
  headerSideRight: { justifyContent: 'flex-end' },
  headerCenter: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  headerRowMobile: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 10,
    zIndex: 30,
  },
  headerSideMobile: { flex: 1 },
  headerSideLeftMobile: { alignItems: 'flex-start' },
  headerSideRightMobile: { alignItems: 'flex-end' },
  headerCenterMobile: { flex: 2, alignItems: 'center', justifyContent: 'center' },
  bottomNavbarMobile: {
    width: '100%',
    marginBottom: Platform.OS === 'ios' ? 10 : 15,
    zIndex: 30,
  },

  // --- Componentes Atómicos de UI ---
  logoCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    paddingVertical: 12,
    paddingHorizontal: 25,
    height: 70,
    borderWidth: 3,
    borderColor: '#B0CFFF',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 150,
  },
  logoTextTitle: { fontSize: 20, fontWeight: '900', color: '#3B629B', lineHeight: 30 },
  logoTextSub: { fontSize: 20, fontWeight: '900', color: '#3B629B', lineHeight: 30 },
  coinsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    paddingVertical: 12,
    paddingHorizontal: 20,
    height: 70,
    borderWidth: 3,
    borderColor: '#B0CFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: 150,
  },
  coinsCardMobile: { height: 52, width: '105%', paddingHorizontal: 16, borderRadius: 14 },
  coinIcon: { width: 32, height: 32, resizeMode: 'contain', marginRight: 10 },
  coinIconMobile: { width: 24, height: 24, marginRight: 8 },
  coinsText: { fontSize: 22, fontWeight: '900', color: '#3B629B' },
  coinsTextMobile: { fontSize: 18 },
  navIsland: {
    backgroundColor: '#EAF2FF',
    borderRadius: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderWidth: 3,
    borderColor: '#B0CFFF',
    height: 70,
  },
  navIslandMobile: { width: '100%', alignSelf: 'center', height: 80, paddingHorizontal: 6, borderRadius: 22 },
  navPill: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 4, paddingHorizontal: 22, marginHorizontal: 10 },
  navPillMobile: { flexDirection: 'column', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 1, marginHorizontal: 1 },
  pillIcon: { width: 54, height: 54, resizeMode: 'contain', marginRight: 8 },
  pillIconMobile: { width: 55, height: 55, resizeMode: 'contain', marginBottom: -8 },
  pillText: { color: '#3B629B', fontSize: 22, fontWeight: '900' },
  pillTextMobile: { color: '#3B629B', fontSize: 14, fontWeight: '900', lineHeight: 16 },
  profileIconMobile: { width: 54, height: 54 },
  profileIconImage: { marginTop: 3, width: 60, height: 60, resizeMode: 'contain' },

  // ================= ESTILOS GLOBALES TIENDA =================
  storeTitle: {
    fontSize: 36,
    fontWeight: '900',
    color: '#fafaffff',
    textAlign: 'center',
    marginBottom: 10,
  },
  storeTitleWeb: {
    fontSize: 42,
    fontWeight: '900',
    color: '#fafaffff',
    textAlign: 'left',
    marginBottom: 12,
    paddingHorizontal: 10,
  },
  featuredItemCard: {
    backgroundColor: '#8cbaff',
    borderRadius: 32,
    width: '100%',
    justifyContent: 'flex-end',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#70a5fa',
  },
  featuredPreviewPlaceholder: { flex: 1, width: '100%' },
  featuredPriceBadge: { bottom: 12, paddingHorizontal: 25 },
  priceBadge: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 6,
    paddingHorizontal: 16,
    borderWidth: 2,
    borderColor: '#e2efff',
  },
  priceCoinIcon: { width: 22, height: 22, resizeMode: 'contain', marginRight: 6 },
  priceText: { fontSize: 14, fontWeight: '900', color: '#000000' },
  itemPreviewPlaceholder: { flex: 1, width: '100%' },

  // ================= ESTRUCTURA MÓVIL (SPLIT VERTICAL) =================
  mainContentMobileSplit: {
    flex: 1,
    width: '100%',
  },
  mobileStaticTopSection: {
    width: '100%',
    paddingBottom: 10,
  },
  featuredItemCardMobile: {
    height: 190,
  },
  mobileScrollingBottomSection: {
    flex: 1,
    width: '100%',
  },
  mobileItemsScrollContent: {
    paddingBottom: 110,
    paddingTop: 5,
  },
  mobileGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
  },
  smallItemCardMobile: {
    backgroundColor: '#8cbaff',
    borderRadius: 24,
    width: '48%',
    height: 160,
    padding: 10,
    justifyContent: 'flex-end',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#70a5fa',
  },

  // ================= ESTRUCTURA DESKTOP WEB (SPLIT HORIZONTAL) =================
  webDashboardLayout: {
    flex: 1,
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    gap: 30,
  },
  featuredItemCardWeb: {
    flex: 1.2,
    height: '100%',
    marginBottom: 0,
  },
  smallItemsContainerWeb: {
    flex: 1.5,
    height: '100%',
  },
  smallItemsScrollWeb: { flex: 1 },
  smallItemsScrollContentWeb: { paddingBottom: 20 },
  webGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 20,
    justifyContent: 'flex-start',
  },
  smallItemCardWeb: {
    backgroundColor: '#8cbaff',
    borderRadius: 28,
    width: '30%',
    minWidth: 150,
    height: 210,
    padding: 14,
    justifyContent: 'flex-end',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#70a5fa',
  },
});